version: '3'
services:
  zk:
    image: zookeeper:3.4
    networks:
      - marathonspawner
    ports:
      - 2181:2181
  mesos-master:
    image: dtaniwaki/mesos-master:1.4.0-2.0.1
    command: mesos-master --registry=in_memory --port=5050 --zk=zk://zk:2181/mesos --log_dir=/var/log/mesos
    networks:
      - marathonspawner
    ports:
      - 5050:5050
    expose:
      - 5050
    depends_on:
      - zk
  mesos-slave:
    image: dtaniwaki/mesos-slave:1.4.0-2.0.1
    command: mesos-slave --port=5051 --master=zk://zk:2181/mesos --work_dir=/sandbox --log_dir=/var/log/mesos --hostname=localhost --isolation=filesystem/linux,docker/runtime --image_providers=docker
    privileged: true
    networks:
      - marathonspawner
    depends_on:
      - mesos-master
    ports:
      - 5051:5051
    expose:
      - 5051
    volumes:
      - ./tmp/sandbox:/sandbox
      - ./tmp/data:/data
    depends_on:
      - mesos-master
  marathon:
    image: dtaniwaki/marathon:1.5.1
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon
    networks:
      - marathonspawner
    depends_on:
      - mesos-master
    ports:
      - 8080:8080
    expose:
      - 8080
  hub:
    build:
      context: '.'
    command: jupyterhub --ip 0.0.0.0 --port 8000 --debug
    user: jupyterhub # The UID is the same as anonymous user in mesos-slave
    environment:
      - JUPYTERHUB_API_IP=hub
      - JUPYTERHUB_API_PORT=8081
      - NOTEBOOK_IMAGE=jupyterhub/singleuser:0.8.1
      - MARATHON_HOST=http://marathon:8080
      - MESOS_USER=anonymous
    networks:
      - marathonspawner
    ports:
      - 8000:8000
      - 8081:8081
    expose:
      - 8000
      - 8081
    depends_on:
      - marathon
networks:
  marathonspawner:
